# Site settings
title: Chris Jimenez
header-img: img/home-bg.jpg
email: chris@chrisjimenez.net
copyright_name: Chris Jimenez
description: "Chris Jimenez, Software & Portfolio"
baseurl: ""
url: "http://code.chrisjimenez.net"
twitter_username: ChrisJimenezNat
photo_site: "http://www.chrisjimenez.net"
github_username:  PiXeL16
facebook_username:  pixel16
email_username:  chris@chrisjimenez.net

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
